FROM docker.io/library/node:16-alpine AS builder
WORKDIR /usr/src/app
COPY package.json .
COPY yarn.lock .
RUN yarn install --production
COPY . .
RUN yarn build

FROM docker.io/library/nginx:1.22.0-alpine AS production
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
COPY --chown=nginx:nginx nginx.conf.template /etc/nginx/templates/
COPY default.conf /etc/nginx/conf.d/default.conf
RUN adduser nginx root
RUN chmod -R 775 /etc/nginx/conf.d && \
    chown -R nginx:root /etc/nginx/conf.d
RUN chgrp -R root /var/cache/nginx /var/run /var/log/nginx && \
    chmod -R 770 /var/cache/nginx /var/run /var/log/nginx
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]