apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      volumes:
        - name: nodejs-secret
          secret:
            secretName: nodejs-secret
      containers:
        - name: nodejs
          image: docker.io/andikabahari/mern-server
          volumeMounts:
            - name: nodejs-secret
              mountPath: '/etc/nodejs-secret'
              readOnly: true
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: jwt_secret
            - name: JWT_EXPR
              value: '3600'
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: mongo_username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nodejs-secret
                  key: mongo_password
            - name: MONGO_IP
              value: '10.80.10.60'
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_DB
              value: 'mern'
            - name: MONGO_URL
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@$(MONGO_IP):$(MONGO_PORT)/$(MONGO_DB)"
            - name: PORT
              value: '5000'
          ports:
            - containerPort: 5000
